name: Publish Image to DockerHub

on:
  push:  # Trigger on every push to the repository
    branches:
      - main  # Change to the desired branch if not `main`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get NPM Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # DockerHub username from secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # DockerHub access token from secrets

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/devops:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/devops:${{ steps.package-version.outputs.current-version }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
